# Copyright 2024-2025 the Pinniped contributors. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

# It seems that Bitnami no longer supports openldap.
# See https://github.com/bitnami/containers/issues/83267
# All existing container images have been migrated from the public catalog (docker.io/bitnami) to
# the “Bitnami Legacy” repository (docker.io/bitnamilegacy), where they will no longer receive updates.
#
# FROM bitnami/openldap:2.6.10

FROM bitnamilegacy/openldap:2.6.10
